export const dummyPostData = [
    {
        id: 1,
        event: '정보통신',
        community: '정보보안기사',
        writerNickname: '페이커',
        writerId: '@faker',
        createdAt: '2023.05.01',
        title: '정보보안기사 2주만에 실기 합격할 수 있었던 방법😊',
        postPeriod: '2주',
        postResult: '합격',
        commentCount: 5,
        likeCount: 10,
        viewNumber: 25,
        isLiked: false,
        isBookmarked: false,
    },
    {
        id: 2,
        event: '정보통신',
        community: '정보처리기사',
        writerNickname: '오너',
        writerId: '@oner',
        createdAt: '2023.05.07',
        title: '정보처리기사 한달만에 실기 합격할 수 있었던 방법😊',
        postPeriod: '1개월',
        postResult: '합격',
        commentCount: 20,
        likeCount: 90,
        viewNumber: 110,
        isLiked: false,
        isBookmarked: false,
    },
    {
        id: 3,
        event: '정보통신',
        community: '정보보안기사',
        writerNickname: '제우스',
        writerId: '@zeus',
        createdAt: '2023.06.01',
        title: '정보보안기사 공부 방법 공유합니다~~',
        postPeriod: '6개월',
        postResult: '합격',
        commentCount: 3,
        likeCount: 40,
        viewNumber: 90,
        isLiked: false,
        isBookmarked: false,
    },
    {
        id: 4,
        event: '정보통신',
        community: '정보보안기사',
        writerNickname: '구마유시',
        writerId: '@gumayusi',
        createdAt: '2023.09.01',
        title: '정보보안기사 2주만에 실기 합격할 수 있었던 방법😊',
        postPeriod: '2주',
        postResult: '합격',
        commentCount: 5,
        likeCount: 10,
        viewNumber: 25,
        isLiked: false,
        isBookmarked: false,
    },
    {
        id: 5,
        event: '정보통신',
        community: '정보보안기사',
        writerNickname: '케리아',
        writerId: '@keria',
        createdAt: '2023.11.01',
        title: '정보보안기사 2주만에 실기 합격할 수 있었던 방법😊',
        postPeriod: '2주',
        postResult: '합격',
        commentCount: 5,
        likeCount: 10,
        viewNumber: 25,
        isLiked: false,
        isBookmarked: false,
    },
    {
        id: 6,
        event: '경영/회계/사무',
        community: '정보보안기사',
        writerNickname: '케리아',
        writerId: '@keria',
        createdAt: '2023.11.01',
        title: '정보보안기사 2주만에 실기 합격할 수 있었던 방법😊',
        postPeriod: '2주',
        postResult: '합격',
        commentCount: 5,
        likeCount: 10,
        viewNumber: 25,
        isLiked: false,
        isBookmarked: false,
    },

];